In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
dataset=pd.read_csv("Churn_Modelling.csv",header=0)

In [3]:
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [4]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


encoding categorical data

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [7]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


one hot encoding

In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [9]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

building ANN

intializing ANN

In [12]:
ann=tf.keras.models.Sequential()

adding the input layer and the first hidden layer


In [13]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

training the ANN


compiling the ANN

In [16]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

train the ANN

In [17]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5978 - accuracy: 0.7426
Epoch 2/100
250/250 [==============================] - 0s 596us/step - loss: 0.4802 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 534us/step - loss: 0.4459 - accuracy: 0.7969
Epoch 4/100
250/250 [==============================] - 0s 554us/step - loss: 0.4321 - accuracy: 0.8064
Epoch 5/100
250/250 [==============================] - 0s 559us/step - loss: 0.4245 - accuracy: 0.8129
Epoch 6/100
250/250 [==============================] - 0s 584us/step - loss: 0.4194 - accuracy: 0.8185
Epoch 7/100
250/250 [==============================] - 0s 639us/step - loss: 0.4152 - accuracy: 0.8229
Epoch 8/100
250/250 [==============================] - 0s 671us/step - loss: 0.4114 - accuracy: 0.8257
Epoch 9/100
250/250 [==============================] - 0s 713us/step - loss: 0.4081 - accuracy: 0.8289
Epoch 10/100
250/250 [==============================] - 0s 542us/step - los

making the prediction and evaluating the model

In [19]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

[[False]]


predicting the test set results

In [20]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1529   66]
 [ 198  207]]


0.868